ingress:
  enabled: true
  host: longhorn.coindefense.duckdns.org
  tls:
    - secretName: longhorn-tls-cert
      hosts:
        - longhorn.coindefense.duckdns.org

defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultDataPath: "/mnt/longhorn"
