replicaCount: 2
clusterDomain: cluster.local

extraEnv: |
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: dns.DNS_PING
  - name: JGROUPS_DISCOVERY_PROPERTIES
    value: dns_query={{ include "keycloak.serviceDnsName" . }}
  - name: CACHE_OWNERS_COUNT
    value: "1

auth:
  adminUser: "admin"
  adminPassword: "admin"

ingress:
  enabled: true
  hostname: "keycloak.coindefense.duckdns.org"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
  tls: true
  secretName: "keycloak-tls"

volumePermissions:
  enabled: true
persistence:
  storageClass: "longhorn"
  size: 10Gi

resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"
  limits:
    memory: "2048Mi" 
    cpu: "1000m"
