apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.101-192.168.0.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: coindfip
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
