auth:
  postgresPassword: "adminpassword"   # PostgreSQL 관리자 비밀번호
  username: "keycloakuser"            # Keycloak용 사용자 이름
  password: "keycloakpassword"        # Keycloak용 사용자 비밀번호
  database: "keycloakdb"              # Keycloak용 데이터베이스 이름

primary:
  persistence:
    enabled: true                     # 영구 스토리지 활성화
    storageClass: "longhorn"          # Longhorn 스토리지 클래스 사용 (필요 시 변경)
    size: 200Gi                         # 스토리지 크기

replicaCount: 1                       # 단일 구성으로 설정
